import type { EduStudent } from "@/app/(dashboard)/hakjeom/education-center/types";

// 가이드 시연용 가짜 학생 데이터
// id는 모두 음수 → 실제 DB 작업에서 배제 (수정/삭제 모달은 가이드 종료 시 자동 닫힘)
const now = new Date().toISOString();

export const EDU_DEMO_STUDENTS: EduStudent[] = [
  {
    id: "-999990",
    name: "홍길동(가이드 예시)",
    phone: "010-1234-5678",
    education_level: "4년제졸업",
    major: "경영학",
    desired_degree: "학사(타전공)",
    status: "등록",
    course_id: 1,
    manager_name: "이규준",
    cost: 1800000,
    unit_price: 150000,
    class_start: "2026-05",
    target_completion_date: "2027-02",
    education_center_name: "한평생교육원",
    all_care: false,
    notes: "가이드 예시 학생 — 실제 데이터 아님",
    registered_at: now,
    created_at: now,
    updated_at: now,
    edu_courses: { id: 1, name: "사회복지사2급 - 신법", created_at: now },
  },
  {
    id: "-999991",
    name: "김민지(가이드 예시)",
    phone: "010-2222-3333",
    education_level: "2년제졸업",
    major: "사회복지",
    desired_degree: "학사",
    status: "사회복지사-실습예정",
    course_id: 1,
    manager_name: "유승현",
    cost: 1500000,
    unit_price: 150000,
    class_start: "2026-04",
    target_completion_date: "2027-01",
    education_center_name: "한평생교육원",
    all_care: true,
    notes: "가이드 예시 학생",
    registered_at: now,
    created_at: now,
    updated_at: now,
    edu_courses: { id: 1, name: "사회복지사 (실습예정)", created_at: now },
  },
  {
    id: "-999992",
    name: "박철수(가이드 예시)",
    phone: "010-4444-5555",
    education_level: "고졸",
    major: null,
    desired_degree: "전문학사",
    status: "수료",
    course_id: 2,
    manager_name: "김하준",
    cost: 1200000,
    unit_price: 100000,
    class_start: "2025-09",
    target_completion_date: "2026-02",
    education_center_name: "한평생교육원",
    all_care: false,
    notes: "가이드 예시 학생",
    registered_at: now,
    created_at: now,
    updated_at: now,
    edu_courses: { id: 2, name: "건강가정사", created_at: now },
  },
];
