// 가이드용 데모 학생 목록 — 실제 DB에 없고, 가이드 활성화 시에만 화면에 보임
// id는 음수로 → handleUpdate가 가짜 학생으로 인식해서 DB 호출 안 함

export interface DemoConsultation {
  id: number;
  name: string;
  contact: string;
  education: string | null;
  reason: string | null;
  click_source: string | null;
  status: string;
  memo: string | null;
  subject_cost: number | null;
  manager: string | null;
  residence: string | null;
  hope_course: string | null;
  counsel_completed_at: string | null;
  counsel_check: string | null;
  current_situation: string | null;
  reaction_point: string | null;
  contact_scheduled_at: string | null;
  created_at: string;
  updated_at: string | null;
}

const now = () => new Date().toISOString();

export const DEMO_LIST: DemoConsultation[] = [
  {
    id: -999999,
    name: "홍길동 (가이드 예시)",
    contact: "010-0000-0000",
    education: null,
    reason: "취업",
    click_source: "가이드",
    status: "상담대기",
    memo: "이 학생은 가이드 예시 데이터입니다. 실제 저장되지 않아요.",
    subject_cost: null,
    manager: null,
    residence: "서울 강남구",
    hope_course: null,
    counsel_completed_at: null,
    counsel_check: null,
    current_situation: "직장인",
    reaction_point: null,
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999998,
    name: "김지영",
    contact: "010-1111-2222",
    education: "4년제 졸업",
    reason: "노후대비",
    click_source: "네이버검색",
    status: "상담완료-높음",
    memo: null,
    subject_cost: 150000,
    manager: "유승현",
    residence: "경기 성남시",
    hope_course: "사회복지사2급 - 신법",
    counsel_completed_at: now(),
    counsel_check: null,
    current_situation: "주부",
    reaction_point: "취업연계",
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999997,
    name: "박철수",
    contact: "010-3333-4444",
    education: "2년제 졸업",
    reason: "이직",
    click_source: "당근채팅",
    status: "상담대기",
    memo: "오후 통화 희망",
    subject_cost: null,
    manager: null,
    residence: "인천 부평구",
    hope_course: "사회복지사2급 - 구법",
    counsel_completed_at: null,
    counsel_check: null,
    current_situation: "직장인",
    reaction_point: null,
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999996,
    name: "이수민",
    contact: "010-5555-6666",
    education: "고졸",
    reason: "취업",
    click_source: "구글검색",
    status: "상담완료-중간",
    memo: null,
    subject_cost: 145000,
    manager: "김하준",
    residence: "서울 송파구",
    hope_course: "건강가정사",
    counsel_completed_at: now(),
    counsel_check: null,
    current_situation: "주부",
    reaction_point: "비싸다",
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999995,
    name: "최예준",
    contact: "010-7777-8888",
    education: "4년제 졸업",
    reason: "취업",
    click_source: "지인소개_김지영",
    status: "지인등록",
    memo: null,
    subject_cost: 140000,
    manager: "박혜경",
    residence: "부산 해운대구",
    hope_course: "사회복지사2급 - 신법",
    counsel_completed_at: now(),
    counsel_check: null,
    current_situation: "직장인",
    reaction_point: null,
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999994,
    name: "정하늘",
    contact: "010-2222-3333",
    education: "3년제 졸업",
    reason: "노후대비",
    click_source: "맘카페",
    status: "상담완료-낮음",
    memo: "재상담 필요",
    subject_cost: null,
    manager: "백은정",
    residence: "대구 수성구",
    hope_course: "사회복지사 (실습예정)",
    counsel_completed_at: now(),
    counsel_check: null,
    current_situation: "주부",
    reaction_point: "비교중",
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999993,
    name: "강민호",
    contact: "010-4444-5555",
    education: "대학원 이상",
    reason: "이직",
    click_source: "네이버검색",
    status: "등록완료",
    memo: null,
    subject_cost: 155000,
    manager: "유승현",
    residence: "광주 서구",
    hope_course: "사회복지사2급 - 신법",
    counsel_completed_at: now(),
    counsel_check: null,
    current_situation: "직장인",
    reaction_point: null,
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999992,
    name: "윤서연",
    contact: "010-6666-7777",
    education: "2년제 중퇴",
    reason: "취업",
    click_source: "대표전화",
    status: "보류",
    memo: "비용 부담 호소",
    subject_cost: null,
    manager: null,
    residence: "대전 유성구",
    hope_course: null,
    counsel_completed_at: null,
    counsel_check: null,
    current_situation: "구직중",
    reaction_point: "할인에반응",
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999991,
    name: "장도윤",
    contact: "010-8888-9999",
    education: "4년제 중퇴",
    reason: "취업",
    click_source: "당근채팅",
    status: "상담대기",
    memo: null,
    subject_cost: null,
    manager: null,
    residence: "울산 남구",
    hope_course: "건강가정사",
    counsel_completed_at: null,
    counsel_check: null,
    current_situation: "구직중",
    reaction_point: null,
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
  {
    id: -999990,
    name: "한지우",
    contact: "010-9999-0000",
    education: "4년제 졸업",
    reason: "노후대비",
    click_source: "인스타그램",
    status: "취소",
    memo: "타기관 이전",
    subject_cost: null,
    manager: "김하준",
    residence: "경기 수원시",
    hope_course: "사회복지사2급 - 구법",
    counsel_completed_at: now(),
    counsel_check: null,
    current_situation: "직장인",
    reaction_point: null,
    contact_scheduled_at: null,
    created_at: now(),
    updated_at: null,
  },
];
