-- ============================================================
-- 학점은행제 통합 관리 시스템 - 통합 DB 스키마
-- ============================================================
-- 주의: consultations 테이블명 충돌로 prefix 적용
--   학점은행제: hakjeom_consultations
--   실습/취업:  practice_consultations
-- ============================================================


-- ============================================================
-- 공통 함수
-- ============================================================

create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;


-- ============================================================
-- 앱 사용자 테이블 (로그인용)
-- ============================================================

create table public.app_users (
  id bigserial not null,
  username text not null unique,
  password_hash text not null,
  display_name text null,
  role text not null default 'staff',
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint app_users_pkey primary key (id),
  constraint app_users_role_check check (role = any (array['admin'::text, 'staff'::text]))
);


-- ============================================================
-- 학점은행제 DB
-- ============================================================

-- 기관협약 테이블
create table public.agency_agreements (
  id bigserial not null,
  category text null,
  region text null,
  institution_name text null,
  contact text null,
  credit_commission text null,
  private_commission text null,
  manager text null,
  memo text null,
  status text null default '협약대기'::text,
  created_at timestamp with time zone null default now(),
  constraint agency_agreements_pkey primary key (id)
);

-- 학점은행제 상담 테이블 (기존 consultations → hakjeom_consultations)
create table public.hakjeom_consultations (
  id bigserial not null,
  name text not null,
  contact text not null,
  education text null,
  reason text null,
  click_source text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  memo text null,
  status text null default '상담대기'::text,
  subject_cost integer null,
  manager text null,
  residence text null,
  hope_course text null,
  counsel_check text null,
  constraint hakjeom_consultations_pkey primary key (id),
  constraint hakjeom_check_status check (
    status = any (array[
      '상담대기'::text,
      '상담중'::text,
      '보류'::text,
      '등록대기'::text,
      '등록완료'::text
    ])
  )
);

create index idx_hakjeom_consultations_created_at on public.hakjeom_consultations using btree (created_at desc);
create index idx_hakjeom_consultations_contact on public.hakjeom_consultations using btree (contact);
create index idx_hakjeom_consultations_click_source on public.hakjeom_consultations using btree (click_source);
create index idx_hakjeom_consultations_status on public.hakjeom_consultations using btree (status);

create trigger update_hakjeom_consultations_updated_at
  before update on hakjeom_consultations
  for each row execute function update_updated_at_column();

-- 연락처 테이블 (credit_bank_contacts)
create table public.credit_bank_contacts (
  id bigint generated by default as identity not null,
  major_category text not null default '',
  sub_category text not null default '',
  name text not null default '',
  contact text not null default '',
  education text not null default '',
  created_at timestamp with time zone not null default now(),
  constraint credit_bank_contacts_pkey primary key (id)
);

-- 민간자격증 상담 테이블
create table public.private_cert_consultations (
  id bigserial not null,
  name text not null,
  contact text not null,
  education text null,
  hope_course text null,
  reason text null,
  click_source text null,
  memo text null,
  counsel_check text null,
  status text null default '상담대기'::text,
  subject_cost numeric null,
  manager text null,
  residence text null,
  major_category text null,
  mamcafe_activity text null,
  created_at timestamp with time zone null default now(),
  constraint private_cert_consultations_pkey primary key (id)
);

-- CSV 임시 스테이징 테이블 (CSV import 버퍼)
create table public.csv_staging (
  id bigint generated by default as identity not null,
  row_type text not null,                 -- 어느 테이블로 넣을지 구분 (hakjeom / cert / practice / employment)
  name text not null default '',
  contact text not null default '',
  education text null,
  major_category text null,
  hope_course text null,
  click_source text null,
  reason text null,
  memo text null,
  status text not null default '상담대기',
  manager text null,
  residence text null,
  counsel_check text null,
  subject_cost integer null,
  created_at timestamp with time zone not null default now(),
  applied_at text null,
  constraint csv_staging_pkey primary key (id)
);


-- ============================================================
-- 자격증 신청 DB
-- ============================================================

-- 자격증 신청 테이블
create table public.certificate_applications (
  id uuid not null default gen_random_uuid(),
  name text not null,
  contact text not null,
  birth_prefix text not null,
  address text not null,
  certificates text[] not null,
  cash_receipt text null,
  photo_url text null,
  order_id character varying(100) null,
  amount integer null default 0,
  payment_status character varying(50) null default 'pending',
  trade_id character varying(100) null,
  mul_no character varying(100) null,
  pay_method character varying(50) null,
  paid_at timestamp with time zone null,
  failed_at timestamp with time zone null,
  failed_message text null,
  cancelled_at timestamp with time zone null,
  address_main character varying(255) null,
  address_detail character varying(255) null,
  is_checked boolean null default false,
  source text null default 'bridge',
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint certificate_applications_pkey primary key (id),
  constraint certificate_applications_order_id_key unique (order_id),
  constraint certificate_applications_trade_id_key unique (trade_id),
  constraint valid_payment_status check (
    (payment_status)::text = any (array[
      'pending'::text, 'paid'::text, 'failed'::text, 'cancelled'::text
    ])
  )
);

create index idx_cert_app_order_id on public.certificate_applications using btree (order_id);
create index idx_cert_app_payment_status on public.certificate_applications using btree (payment_status);
create index idx_cert_app_paid_at on public.certificate_applications using btree (paid_at);
create index idx_cert_app_trade_id on public.certificate_applications using btree (trade_id);
create index idx_certificate_applications_source on public.certificate_applications using btree (source);

-- 결제 로그
create table public.payment_logs (
  id uuid not null default gen_random_uuid(),
  app_id uuid not null,
  action character varying(100) not null,
  amount integer null,
  request_data jsonb null,
  response_data jsonb null,
  error_message text null,
  ip_address inet null,
  user_agent text null,
  created_at timestamp with time zone null default now(),
  constraint payment_logs_pkey primary key (id),
  constraint payment_logs_app_id_fkey foreign key (app_id)
    references certificate_applications (id) on delete cascade
);

create index idx_payment_logs_app_id on public.payment_logs using btree (app_id);
create index idx_payment_logs_action on public.payment_logs using btree (action);
create index idx_payment_logs_created_at on public.payment_logs using btree (created_at);


-- ============================================================
-- 실습/취업 DB
-- ============================================================

-- 실습/취업 상담 테이블 (기존 consultations → practice_consultations)
create table public.practice_consultations (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  contact character varying(20) not null,
  type character varying(50) null default 'consultation',
  progress character varying(100) null,
  employment_consulting boolean null default false,
  employment_connection boolean null default false,
  student_status character varying(50) null default '상담대기',
  practice_place character varying(200) null,
  employment_after_cert character varying(50) null,
  education character varying(100) null,
  hope_course text null,
  reason text null,
  click_source character varying(100) null,
  memo text null,
  status character varying(50) null default '상담대기',
  subject_cost integer null,
  manager character varying(100) null,
  residence character varying(200) null,
  study_method character varying(50) null,
  address character varying(500) null,
  is_completed boolean null default false,
  notes text null,
  service_practice boolean null default false,
  service_employment boolean null default false,
  practice_planned_date character varying(6) null,
  employment_hope_time text null,
  employment_support_fund boolean null,
  created_at timestamp with time zone null default current_timestamp,
  updated_at timestamp with time zone null default current_timestamp,
  constraint practice_consultations_pkey primary key (id)
);

create index idx_practice_consultations_name on public.practice_consultations using btree (name);
create index idx_practice_consultations_contact on public.practice_consultations using btree (contact);
create index idx_practice_consultations_status on public.practice_consultations using btree (status);
create index idx_practice_consultations_student_status on public.practice_consultations using btree (student_status);
create index idx_practice_consultations_type on public.practice_consultations using btree (type);
create index idx_practice_consultations_created_at on public.practice_consultations using btree (created_at);

create trigger update_practice_consultations_updated_at
  before update on practice_consultations
  for each row execute function update_updated_at_column();

-- 취업 신청 테이블
create table public.employment_applications (
  id uuid not null default gen_random_uuid(),
  name text not null,
  gender text not null,
  contact text not null,
  birth_date text not null,
  address text not null,
  address_detail text null,
  zonecode text null,
  desired_job_field text not null,
  employment_types text[] not null,
  has_resume boolean not null,
  certifications text null,
  payment_amount integer not null default 110000,
  payment_status text not null default 'pending',
  payment_id text null,
  privacy_agreed boolean not null default false,
  terms_agreed boolean not null default false,
  click_source text null,
  status text not null default 'pending',
  created_at timestamp with time zone not null default now(),
  constraint employment_applications_pkey primary key (id),
  constraint employment_applications_gender_check check (gender = any (array['남'::text, '여'::text])),
  constraint employment_applications_payment_status_check check (
    payment_status = any (array['pending'::text, 'requested'::text, 'failed'::text, 'paid'::text])
  )
);

-- 실습 신청 테이블
create table public.practice_applications (
  id uuid not null default gen_random_uuid(),
  name character varying(100) not null,
  gender character varying(5) not null,
  contact character varying(20) not null,
  birth_date character varying(10) not null,
  address character varying(500) not null,
  address_detail character varying(500) null,
  zonecode character varying(10) null,
  practice_type character varying(100) not null,
  desired_job_field text not null,
  employment_types text[] null default '{}',
  has_resume boolean not null default false,
  certifications text null,
  payment_amount integer null default 110000,
  payment_status character varying(20) null default 'pending',
  payment_id character varying(255) null,
  privacy_agreed boolean not null default false,
  terms_agreed boolean not null default false,
  click_source character varying(500) null,
  status character varying(20) null default 'pending',
  memo text null,
  manager character varying(100) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint practice_applications_pkey primary key (id),
  constraint practice_applications_gender_check check (
    (gender)::text = any (array['남'::text, '여'::text])
  )
);

create trigger practice_applications_updated_at
  before update on practice_applications
  for each row execute function update_updated_at();


-- ============================================================
-- 채널 관리 DB (korhrdsocial)
-- ============================================================

create table public.channels (
  id text not null,
  name text not null,
  type text not null default 'mamcafe',
  created_at timestamp with time zone not null default now(),
  constraint channels_pkey primary key (id)
);


-- ============================================================
-- 결제 주문 DB (creaditbridge)
-- ============================================================

-- 주문 테이블
create table public.orders (
  id bigserial not null,
  order_id text not null unique,
  amount integer not null,
  order_name text not null,
  product_type text null,
  billing_cycle text null,
  customer_name text not null,
  customer_phone text not null,
  status text not null default 'pending',
  trade_id text null,
  mul_no text null,
  pay_method text null,
  paid_at timestamp with time zone null,
  failed_at timestamp with time zone null,
  failed_message text null,
  cancelled_at timestamp with time zone null,
  application_id integer null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint orders_pkey primary key (id),
  constraint orders_status_check check (
    status = any (array['pending'::text, 'paid'::text, 'failed'::text, 'cancelled'::text])
  )
);

create trigger orders_updated_at
  before update on orders
  for each row execute function update_updated_at();

-- 결제 취소 테이블
create table public.payment_cancellations (
  id uuid not null default gen_random_uuid(),
  app_id uuid not null,
  mul_no text not null,
  cancel_type text not null,
  cancel_amount integer not null,
  cancel_reason text null,
  status text not null default 'pending',
  cancelled_mul_no text null,
  cancellation_date timestamp with time zone null,
  payback_amount integer null,
  payback_bank text null,
  payback_account text null,
  payback_account_holder text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint payment_cancellations_pkey primary key (id),
  constraint payment_cancellations_app_id_fkey foreign key (app_id)
    references certificate_applications (id) on delete cascade,
  constraint payment_cancellations_cancel_type_check check (
    cancel_type = any (array['full'::text, 'partial'::text, 'request'::text])
  ),
  constraint payment_cancellations_status_check check (
    status = any (array['pending'::text, 'approved'::text, 'rejected'::text])
  )
);

create index idx_payment_cancellations_app_id on public.payment_cancellations using btree (app_id);

create trigger payment_cancellations_updated_at
  before update on payment_cancellations
  for each row execute function update_updated_at();
